- README.md
- lib/montrose/chainable.rb
- lib/montrose/options.rb
- lib/montrose/refinements/array_concat.rb
- spec/montrose/chainable_spec.rb
Selected `Chainable` methods should accept both varargs and array-like objects:
The following would be equivalent:
```ruby
Montrose.monthly.day_of_month(6, 7, 8)
Montrose.monthly.day_of_month([6, 7, 8])
Montrose.monthly.day_of_month(6..8)
```
> Chainable varargs

- lib/montrose/clock.rb
- lib/montrose/frequency.rb
- lib/montrose/options.rb
- lib/montrose/recurrence.rb
- spec/montrose/options_spec.rb
- spec/montrose/recurrence_spec.rb
We want to avoid mixing default options with the deserialized version of a Recurrence.
> Fewer instance default options

- lib/montrose/clock.rb
- lib/montrose/frequency.rb
- lib/montrose/options.rb
- lib/montrose/rule/time_of_day.rb
- lib/montrose/utils.rb
- spec/montrose/options_spec.rb
- spec/montrose/recurrence_spec.rb
- spec/montrose/rule/time_of_day_spec.rb
- spec/spec_helper.rb
Changes the internal representation of the `:at` option to represent the
hour and minute parts. Using `:at` no longer sets the `:starts` option
as a side effect. Instead, a new read-only calculated option,
`:start_time` is used internally to represent the logical start of the
recurrence. Using `:starts` and `:at` simultaneously will treat the
`:starts` time as a date and use the first occuring `:at` time of day to
calculate the recurrence start time.
Fixes #42
> Introduce Options#start_time

- README.md
- lib/montrose/options.rb
- lib/montrose/rule/day_of_month.rb
- lib/montrose/rule/day_of_year.rb
- lib/montrose/rule/nth_day_of_month.rb
- lib/montrose/utils.rb
- spec/montrose/rule/total_spec.rb
- spec/montrose/utils_spec.rb
- spec/spec_helper.rb
Time parsing and current time should respect `Time.zone` when configured.
Fixes #8
> Respect time zone

- lib/montrose/recurrence.rb
- spec/montrose/recurrence_spec.rb
Delegates to Recurrence#to_hash. Fixes bug where #to_json would get
stuck in an infinite loop due to default behavior imposed by
ActiveSupport
Fixes #34
> Implement Recurrence#to_json

- lib/montrose/frequency/weekly.rb
- lib/montrose/utils.rb
- spec/montrose/utils_spec.rb
When working with start and end dates, `ActiveSupport::TimeWithZone` objects passed in are being converted using `to_time` which leads to some undesired behavior calculating recurrences.  Passing a string doesn't solve the issue due to [this](https://github.com/rossta/montrose/blob/master/lib/montrose/recurrence.rb#L81) `Options.merge` call leading to the parsed TimeWithZone object being passed back into `as_time` and then converted `to_time`.
**Current behavior**
```ruby
Montrose.r(every: "month").events.first
=> Wed, 27 Jul 2016 09:14:59 UTC +00:00
Montrose.r(every: "month", starts: Time.zone.now).events.first
=> "2016-07-27T04:15:48.606-05:00"
Montrose.r(every: "month", starts: Time.zone.now.to_s).events.first
=> "2016-07-27T04:21:48.000-05:00"
```
**New behavior**
```ruby …
```
> Respect TimeWithZone objects passed into as_time during assignment

- README.md
Update incorrect monthly example, `on` option used for days_of_week.
```ruby
Montrose.every(:month, on: [2, 15], total: 10)
Montrose::ConfigurationError: Did not recognize day 15, must be one of ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
```
> Update Readme example

- spec/spec_helper.rb
To avoid small percentage change failures in code coverage during build.
> Add maximum coverage drop setting for Simplecov

- lib/montrose/recurrence.rb
- spec/montrose/recurrence_spec.rb
`Recurrence#include?` optimization introduced bug where given timestamp occurring before the start point of a recurrence (if it exists) could return true.
> Bug fix recurrence include

- .travis.yml
- Rakefile
Update rubies and publish docs on master builds
> Update travis build

- lib/montrose/options.rb
- spec/spec_helper.rb
Creates duplication with already-present :starts and :until options
> Remove :between from defined options

- lib/montrose/recurrence.rb
- spec/montrose/recurrence_spec.rb
When calling `Montrose::Recurrence.load(nil)`, let's avoid a `TypeError`, ex:
```
TypeError: no implicit conversion of nil into String
.../ruby/2.2.3/gems/json-2.0.2/lib/json/common.rb:156:in `initialize'
.../ruby/2.2.3/gems/json-2.0.2/lib/json/common.rb:156:in `new'
.../ruby/2.2.3/gems/json-2.0.2/lib/json/common.rb:156:in `parse'
.../montrose/lib/montrose/recurrence.rb:236:in `load'
```
> Handle nil for deserialization in Recurrence.load

- lib/montrose/recurrence.rb
- spec/montrose/recurrence_spec.rb
The following raises an error:
```ruby
Montrose::Recurrence.dump(every: :day)
```
This successfully serialize the recurrence options. Later we can validate the hash.
> Handle JSON in Recurrence.dump

- lib/montrose/recurrence.rb
- spec/montrose/recurrence_spec.rb
The following raises an error:
```ruby
Montrose::Recurrence.dump(every: :day)
```
This successfully serialize the recurrence options. Later we can validate the hash.
> Handle dump of hash for Recurrence serialization

- lib/montrose/recurrence.rb
- spec/montrose/recurrence_spec.rb
We should be able to handle
```ruby
Montrose::Recurrence.load("") # => nil
```
Currently throws a JSON parse error.
> Handle blank object in Recurrence.load

- .travis.yml
Installation of rainbow failing for ruby 2.3. See
https://github.com/sickill/rainbow/issues/44
> Ensure latest version of rubygems on travis

- lib/montrose/options.rb
- lib/montrose/rule.rb
- lib/montrose/rule/after.rb
- lib/montrose/rule/before.rb
- lib/montrose/rule/between.rb
- lib/montrose/rule/total.rb
- lib/montrose/stack.rb
- spec/montrose/options_spec.rb
- spec/montrose/recurrence_spec.rb
- spec/montrose/rule/after_spec.rb
- spec/montrose/rule/before_spec.rb
- spec/montrose/rule/between_spec.rb
- spec/montrose/rule/day_of_month_spec.rb
- spec/montrose/rule/day_of_week_spec.rb
- spec/montrose/rule/total_spec.rb
Previously, the `:between` option served as a shorthand for `:starts` to `:until`. Now, when both `:starts` and `:between` are provided, the recurrence will behave as if anchored by the given `:starts` option, but filtered through the given `:betweeen` option. 
Fixes #82
> Add separate filter for :between option

- montrose.gemspec
- spec/spec_helper.rb
The specs pass on activesupport 5.1 so there's no reason not to allow it.
> Bump activesupport version

- lib/montrose/frequency.rb
- lib/montrose/frequency/daily.rb
- lib/montrose/frequency/hourly.rb
- lib/montrose/frequency/monthly.rb
- lib/montrose/frequency/weekly.rb
- lib/montrose/frequency/yearly.rb
- spec/montrose/frequency/daily_spec.rb
- spec/montrose/frequency/hourly_spec.rb
- spec/montrose/frequency/monthly_spec.rb
- spec/montrose/frequency/weekly_spec.rb
- spec/montrose/frequency/yearly_spec.rb
I use this gem to save some recurring events in a database. Sometimes I need to generate a crontab from a list of these recurrences, for which these shortcuts are handy. 
I understand this may have some caveats given the unspecified behavior of crontab extensions. Still, I assume this is a common enough scenario for users of this gem, so please consider including this.
To use them, one can do the following:
```ruby
recurrence = # retrieve Montrose::Recurrence object here
Montrose::Frequency.from_options(recurrence.to_h).to_cron # generates cron entry
```
> Adding to_cron method to Frequency

- .rubocop.yml
- lib/montrose/frequency/weekly.rb
- lib/montrose/frequency/yearly.rb
- lib/montrose/options.rb
- lib/montrose/recurrence.rb
- lib/montrose/rule/nth_day_of_month.rb
- lib/montrose/rule/nth_day_of_year.rb
- montrose.gemspec
- spec/montrose/examples_spec.rb
- spec/montrose/recurrence_spec.rb
- spec/spec_helper.rb
Fixes #105 
Previously, montrose was interpreting the following options as "2nd friday of year", when it semantically makes more sense to interpret at "2nd friday of month 1"
```ruby
Montrose.yearly(month: 1, day: {friday: [2]} )
```
> Bug fix: nth day of week in month in yearly interval

- montrose.gemspec
Rails 6 is currently in [beta2](https://weblog.rubyonrails.org/2019/2/25/Rails-6-0-beta2-released/) and some larger shops are already running it in production; this PR updates the dependency constraints to allow for Rails 6.
> Expand Active Support constraint to allow rails 6

- .rubocop.yml
- lib/montrose/options.rb
- lib/montrose/rule/after.rb
- spec/montrose/clock_spec.rb
- spec/montrose/examples_spec.rb
- spec/montrose/options_spec.rb
- spec/montrose/recurrence_spec.rb
Changes the behavior of recurrences with `:at` to ensure instances occur after the given (or implicit) start time.  
For example, if the current time is 12noon local, a recurrence without a `:starts` option and with `:at => %[7am 7pm]` would previously have returned an event for 7am _on today's date_, even though that event is in the past. Though the implicit start time is the current time, the behavior was implemented assuming developers would want all occurrences of the `:at` time on the current date. Citing issues #103, #110 and #117, developers have been confused this behavior.
Now, with the above options, the first event returned will be 7pm, which would be the first event after the implicit start time of 12noon.
To retain the existing behavior, recurrences will need to specify an …
> Ensure :at events recur after start time

- lib/montrose/recurrence.rb
- spec/montrose/recurrence_spec.rb
Fixes #113 
Define Recurrence#as_json
Previously it was impossible to save a non ending recurrence in ActiveRecord: 
```ruby
event = RecurringEvent.new
event.recurrence = Montrose.weekly
event.save # infinite loop
```
Because of:
```ruby
Montrose.weekly.as_json # infinite loop
```
After this commit everything is fixed :)
> Bug fix: Define Recurrence#as_json

- lib/montrose/schedule.rb
- spec/montrose/schedule_spec.rb
- spec/spec_helper.rb
Implements `Schedule.dump` and `Schedule.load` to support serialization, as for ActiveRecord.
> Schedule serialization

- README.md
- lib/montrose/schedule.rb
- spec/montrose/schedule_spec.rb
Adds:
* `Schedule#each`
* `Schedule#to_json`
* `Schedule#as_json`
* `Schedule#to_yaml`
* README updates
> Make schedule enumerable and serializable

- montrose.gemspec
Current version of `montrose` only allows it to be used with Rails `<= 6.0`, which won't work for Rails `6.0.1` (released 2019-11-05).
This PR updates the gemspec dependency to allow `montrose` to work with any Rails `>= 4.1` and `<= 7.0`, with the result that it can now be used with any Rails `6+` application.
I tested on one of my prodution apps where I modified my Gemfile from `rails 6.0` to `rails 6.0.1` and it would break when running `bundle update rails`.
Issue was resolved when I forked `montrose` and updated the dependency to allow `rails <= 7.0`.
If `montrose` is going to resolve this in one of its planned releases, please disregard this PR and I'll use my forked version until the official version is ready.
Thanks for the work on `montrose`, it's an awesome gem and I appreciate …
> Allow compatibility with Rails 6.0.1+ 

- gemfiles/activesupport_6.0.gemfile
ActiveSupport 6.0 has been officially released.
> Update activesupport 6.0 gemfile

- lib/montrose/recurrence.rb
- spec/montrose/recurrence_spec.rb
After using montrose on a project I noticed that the `finite?` method was returning the end date instead of a boolean. While I was at it I added the `infinite?` shortcut to make the code a bit nicer.
Let me know if there's anything you would like me to clean up/change.
Thanks :)
> Ensure finite? returns a boolean; add infinite? method

- lib/montrose.rb
- lib/montrose/chainable.rb
- lib/montrose/options.rb
- lib/montrose/rule.rb
- lib/montrose/rule/covering.rb
- lib/montrose/stack.rb
- spec/montrose/chainable_spec.rb
- spec/montrose/examples_spec.rb
- spec/montrose/options_spec.rb
- spec/montrose/rule/covering_spec.rb
**Breaking change**
Previous, `Montrose.between` acted as both a convenience for `starts` and `ùntil` as well as providing "masking" behavior to address a [feature request](https://github.com/rossta/montrose/issues/82). This created some ambiguous behavior and compromised chaining, as noted in #131. 
This PR addresses the ambiguity by introducing a new option, `:covering` to provide the masking behavior without affecting `:starts` and `:until`. The `:between` option will now be used solely as a shorthand for `:starts` and `:until` and will be normalized as suggested in #131.
A temporary setting can be used to retain the legacy behavior of `:between` to assist with the upgrade, e.g. update settings in serialized Recurrences in a database:
```rb
Montrose.enable_deprecated_between_masking = …
```
> Add Montrose.covering to disambiguate Montrose.between behavior

- lib/montrose.rb
- lib/montrose/recurrence.rb
- spec/montrose/examples_spec.rb
- spec/montrose/frequency/weekly_spec.rb
- spec/montrose/rule/covering_spec.rb
When using an interval, an infinite recurrence can return incorrect results for `#include?`.
The `#include?` method optimization for infinite recurrences is adjusted to take the given interval into account.
Fixes #132
> Fix weekly interval include

- lib/montrose/options.rb
- lib/montrose/rule/during.rb
- lib/montrose/rule/time_of_day.rb
- lib/montrose/time_of_day.rb
- spec/montrose/options_spec.rb
- spec/montrose/rule/during_spec.rb
Previously, a recurrence with a during rule that spans overnight would not return expected results. 
Now:
```ruby
r = Montrose.hourly.during('11pm-3am').starts(Time.now).until(Time.now + 1.day)
=> #<Montrose::Recurrence:708 {:every=>:hour, :starts=>2021-02-03 21:21:01 -0500, :until=>2021-02-04 21:21:01 -0500, :during=>[[[23, 0, 0], [23, 59, 59]], [[0, 0, 0], [3, 0, 0]]]}>
r.events.to_a
=> [
2021-02-03 23:21:01 -0500, 
2021-02-04 00:21:01 -0500, 
2021-02-04 01:21:01 -0500, 
2021-02-04 02:21:01 -0500
]
```
Fixes #124
> Make During rule work for time range spanning midnight

- lib/montrose/options.rb
```console
NameError: undefined local variable or method `block' for #<Montrose::Options {:interval=>1}>
from /gems/ruby/2.7.0/gems/montrose-0.12.0/lib/montrose/options.rb:152:in `fetch'
```
or the block check should be removed
> Fix Montrose::Options#fetch

- lib/montrose/clock.rb
- spec/montrose/clock_spec.rb
The current implementation of `tick` and `peek` method in `Clock` class is slow for large number of `:at` values for a modestly large date range. For example:
```
recurrence = Montrose.r({:every=>"day", :at=>["9:00", "9:30", "9:45", "10:00", "10:15", "10:30", "10:45", "11:00", "11:15", "11:45", "12:00", "12:15", "12:30", "12:45", "13:00", "13:15", "13:30", "14:00", "14:15", "14:30", "14:45", "15:00", "15:15", "15:30", "15:45", "16:00", "16:30", "16:45", "17:00", "17:15", "17:30", "17:45", "18:00", "18:15", "18:45", "19:00", "19:15", "19:30", "19:45", "20:00", "20:15", "20:30", "21:00", "21:15", "21:30", "21:45", "22:00", "22:15", "22:30", "22:45"], :starts=>Time.current, :until=>30.days.from_now, :interval=>1})
recurrence.events
```
Current implementation takes an average of 500-550ms. …
> Change how clock ticks to O(n)

- .circleci/config.yml
- Gemfile.lock
- gemfiles/activesupport_7.1.gemfile
- montrose.gemspec
It would be great to use rails 7.1 with this gem, so I have attempted to add support base of the [7.0 update](https://github.com/rossta/montrose/commit/2656999643b3f7791c9b72a4c6f9ddee2a55c9b7)
> chore: support rails 7.1
